# Site settings
title: Kihonkai
email: dev@kihonkai.com
description: >
  My small space of the Internet to talk about programming,
  photography or anything else that takes my interest.
baseurl: "" 
url: "http://kihonkai.com" # the base hostname & protocol for your site
github_username:  kihonkai

collections:
 content:
  output: true
  permalink: content/:title/

# Build settings
markdown: kramdown

# post settings
permalink: posts/:title